---
- name: Ensure a pod exists for nginx.
  containers.podman.podman_pod:
    name: nginx
    state: created
    recreate: true
    publish:
      - 80:80
      - 443:443

- name: Ensure nginx container exists.
  containers.podman.podman_container:
    pod: nginx
    name: nginx-container
    image: "{{ nginx_image_name }}:{{ nginx_image_tag }}"
    state: created
    restart_policy: always
    volumes:
      - "{{ nginx_conf_path }}:/etc/nginx/conf.d:Z"
      - "{{ nginx_html_path }}:/usr/share/nginx/html:Z"
      - "{{ nginx_tmp_path }}:/var/www/tmp:z,ro"
      - "{{ nginx_certs_path }}:/etc/certs:z,ro"

- name: Ensure default template is installed.
  ansible.builtin.template:
    src: templates/default.conf.j2
    dest: "{{ nginx_conf_path }}/default.conf"
    force: true
    mode: "0644"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Ensure default index.html is installed.
  ansible.builtin.template:
    src: templates/index.html.j2
    dest: "{{ nginx_html_path }}/index.html"
    force: true
    mode: "0644"
    owner: "{{ nginx_user }}"
    group: "{{ nginx_user }}"

- name: Generate systemd units for nginx.
  containers.podman.podman_generate_systemd:
    name: nginx
    dest: "/home/{{ nginx_user }}/.config/systemd/user/"
    restart_policy: "always"

- name: Ensure systemd units are started and enabled for nginx.
  ansible.builtin.systemd:
    scope: user
    daemon_reload: true
    name: pod-nginx
    enabled: true
    state: restarted
