---
- name: Converge
  hosts: all

  vars_files:
    - vars/main.yml

  tasks:
    - name: Remove nginx pod.
      containers.podman.podman_pod:
        name: nginx
        state: absent

    - name: "Include palekiwi.nginx"
      ansible.builtin.include_role:
        name: "palekiwi.nginx"
