---
- name: Converge
  hosts: all

  tasks:
    - name: "Include palekiwi.nginx"
      ansible.builtin.include_role:
        name: "palekiwi.nginx"

    - name: Copy test template.
      ansible.builtin.copy:
        src: files/default.conf
        dest: /srv/nginx/conf.d
        force: true
        mode: "0644"
        owner: vagrant
        group: vagrant
